M7R0
I$abc=6"%&falseGE\[l)%%ptb2Gt+6#%"nG6&%&DeltaG%"aG%"bG%"cGF$F$C&>8%-%&coeffG6$9
$*$%"xG""#>8&-F46$F6F8>8'-F46%F6F8""!@%/F2FB-I'printfG6$%*protectedG%(_syslibG6
#Q=Khong~la~phuong~trinh~bac~2!F$C*-FF6#Q/Phuong~trinh:|+F$-FF6$Q(%A~=~0|+F$F6-
FF6#Q=Phuong~trinh~co~cac~he~so:~|+F$-FF6&Q5a=~%A;~b=~%A;~c=%A~|+F$F2F;F?>8$,&*
$F;F9"""*&F2FgnF?Fgn!"%-FF6#Q,Tinh~Delta:F$-FF6$Q-Delta~~=%A~|+F$FZ@'2FBFZC$-FF
6#QKPhuong~trinh~co~2~nghiem~thuc~phan~biet!~|+F$-%&printG6$/&F86#Fgn,$*&,&F;!"
"-I%sqrtG6$FHFI6#FZFgnFgnF2F_p#FgnF9/&F86#F9,$*&,&F;F_pF`pF_pFgnF2F_pFdp/FZFBC$
-FF6#Q>Phuong~trinh~co~nghiem~kep!~|+F$-Fgo6#/F8,$*&F;FgnF2F_p#F_pF9C$-FF6#Q?Ph
uong~trinh~co~nghiem~phuc!~|+F$-Fgo6$/Fjo,$*&,&F;F_p*&^#FgnFgn-Fap6#,$FZF_pFgnF
gnFgnF2F_pFdp/Ffp,$*&,&F;F_p*&^#F_pFgnFbrFgnFgnFgnF2F_pFdpF$F$F$6#Fgn%%ptb3Gt+F
)6(F,F-F.F/%"dG%"kGF$F$C'>F2-F46$F6*$F8""$>F;F3>F?F<>8(F@@%FD-FF6#Q>Khong~la~ph
uong~trinh~bac~3!|+F$C-FMFP-FF6#Q<Phuong~trinh~co~cac~he~so:|+F$-FF6'Q>a=~%A;~b
=~%A;~c=~%A~;~d=~%A~|+F$F2F;F?Fjs>FZ,&FfnFgnFhn!"$-FF6#Q.Tinh~Delta:~|+F$-FF6$Q
,Delta~=~%A|+F$FZ@$0FBFZ>8),$*&,(*(F2FgnF;FgnF?Fgn""**$F;Ffs!"#*&F2F9FjsFgn!#FF
gn-Fap6#*$-%$absGFcpFfsF_pFdp@$2FZFBC$-FF6#QFPhuong~trinh~co~mot~nghiem~duy~nha
t!|+F$-Fgo6#/F8,&*(-Fap6#F_vFgnF2F_p,&*$,&FbuFgn-Fap6#,&*$FbuF9FgnFgnFgnFgn#Fgn
FfsFgn*$,&FbuFgnFawF_pFewFgnFgnFewFdq#F_pFfs@$F[qC$-FF6#Q=Phuong~trinh~co~nghie
m~kep!|+F$-Fgo6#/F8,$*&,&F;Fgn*$,&FhuFgnFjuF[vFewFgnFgnF2F_pFhw@$Fao@&1-%&evalf
G6#-F`v6#FbuFgnC$-FF6#Q;Phuong~trinh~co~3~nghiem!|+F$-Fgo6%/Fjo,$*&,&*&F`pFgn-I
$cosG6$FHFI6#,$-I'arccosG6$FHFIF]yFewFgnF9F;F_pFgnF2F_pFew/Ffp,$*&,&*&F`pFgn-Fj
y6#,&F^zFew%#piG#FiuFfsFgnF9F;F_pFgnF2F_pFew/&F86#Ffs,$*&,&*&F`pFgn-Fjy6#,&F^zF
ewFiz#F9FfsFgnF9F;F_pFgnF2F_pFew2FgnFixC$Fdv-Fgo6#/F8,&*,F\wFgnF\yFgnF2F_pFbuF_
p,&*$,&F\yFgn-Fap6#,&FdwFgnF_pFgnFgnFewFgn*$,&F\yFgnF`\lF_pFewFgnFgnFewFdqFhwF$
F$F$6#Fgn%'changeGt+F)F$F$F$-%&latexG6#F6F$F$F$6#Fgn%&blpt1Gt+6$%#ptGF86,F-F.%%
tempG%'nghiemG%"tG%(giatribG%#vnG%$vsnG%$ndnG%"iGF$F$C)>F;,&-%$lhsGFj\lFgn-%$rh
sGFj\lF_p>FZ-F46$F;9%>F2-F46%F;Fc^lFB>8*Q8Phuong~trinh~vo~nghiem|+F$>8+Q;phuong
~trinh~vo~so~nghiem|+F$>8,Q@Phuong~trinh~nghiem~duy~nhat~!|+F$@%-%%typeG6$FZ%(n
umericG@%0FZFB-FF6$-%$catG6$F^_lQ'x~=~%aF$,$*&FZFgnF2F_pF_p@%FD-FF6#F[_l-FF6#Fh
^lC(>F?<#-I&solveG6$FHFIFcp-FF6$Q1+~Voi~m~=~%a~=>~F$F?>Fbu-%%subsG6$<#/%"mGFjsF
2@%/FbuFB-FF6#-Fj_l6$F[_lQ"|+F$-FF6#-Fj_l6$Fh^lFjal-FF6$Qco+~Voi~m~khac~cac~pha
n~tu~thuoc~%a~~=>~~Phuong~trinh~co~nghiem~duy~nhat!|+F$F?-Fgo6#/Fc^lF]`lF$F$F$6
#F9%(checkreGt+6$F*F-6(%"uG%%sizeG%$minGFa]lFh]l%'resultGF$F$C*6(*&%&LocalGFgnF
ZFgnFjsF;F?F2%&resulG>FZ7#-Fh`lFj\l>F2-%%nopsGFcp>F;,&-%#opG6$FgnFZFgnFc^lF_p>F
?Fgn?(FjsFgnFgnF2I%trueG7'Q;Complete~the~square~in~x,~6"%ht#mrow(mrow(mn("4"),m
o("&InvisibleTimes;"),msup(mfenced(mrow(mi("x"),mo("&plus;"),mfrac(mn("21"),mn(
"8")))),mn("2"))),mo("&minus;"),mfrac(mn("729"),mn("16")))GFgn7&Fbdl,&*$,&F8Fgn
#"#@"")FgnF9""%#!$H("#;FgnQ[q#~Complete~the~square~in~x,~~4*x^2+21*x-18|+Studen
t:-Precalculus:-CompleteSquare(4*x^2+21*x-18,x)FcdlQgqTypesetting:-mover(Typese
tting:-mo("&rarr;"),Typesetting:-mtext("Complete~the~square~in~x,~~4*x^2+21*x-1
8"))Fcdl"%+6@$2-Fjx6#-F`v6#,&-F\dl6$FjsFZFgnFc^lF_p-Fjx6#-F`v6#F;C$>F;Fjel>F?Fj
s>Fbu-F\dl6$F?FZ@%-Fb_l6$Fbu%(integerGO-I&roundG6$FHFI6#Fc^lOFc^lF$F$F$6#F9%'ho
rnerGt+F)6*%'StringG%"QGI"DG6$FHFIF/FjblF-Fh]lF`sF$F$C)6-*&FaclFgnF;FgnF2Fh^lFb
uF.F?F_sFZ%"sGFa]lF[_l-I%withG6$FHFI6#I&queueG6$FHFI-F]hl6#I,StringToolsG6$FHFI
>FZQ!F$>F2-%$newGF$>F;-%'degreeGFj\l@%/F;FfsC$-Fgo6#Q/Start~to~solveF$-F\sFj\lC
,>F?-F46$F6)F8F;-%(enqueueG6$F2F?>Fjs7#-Fh`lF=>Fbu-F\dl6$FgnFjs?(Fh^lFgnFgn,&F;
FgnF_pFgnF`dlC$-F[jl6$F2,&*&FbuFgnF?FgnFgn-F46$F6)F8,&F;FgnFh^lF_pFgn>F?Fhjl>F[
_l-%'lengthG6#F2?(F$FgnFgnF$4-%&emptyGFb[mC%@$0-%&frontGFb[mFB@&2FBFj[m@%/F[_lF
`[m>FZ-Fj_l6$FZ*&Fj[mFgn)F8FdjlFgn>FZ-Fj_l6'FZQ"+F$Fj[mQ"*F$Fd\m2Fj[mFB@%F_\m>F
ZFa\m>FZ-Fj_l6'FZQ"-F$-F`v6#Fj[mFi\mFd\m-%(dequeueGFb[m>F;Fdjl>FZ-%&parseG6$FZ%
*statementG*&-FF6$QCTa~nham~duoc~mot~nghiem~la~x~=~%A|+F$FbuFgn-FF6&QAVay~ta~co
,~%A~<=>~(x-%A)*(%A)=0|+F$F6FbuFZFgn-%'HornerGFcpF$F$F$6#Fgn%&blpt2Gt+F^]l6-Fa]
lF-F.F/%&deltaG%(nghiemaG%,nghiemdeltaGFh]lFe]l%#nkG%$npbGF$F$C)>FZF[^l>F2-F46$
FZ*$Fc^lF9>F;-F46$FZFc^l>F?-F46%FZFc^lFB>Fjs,&FfnFgn%#acGFin@%-Fb_l6$F2Fd_l@$FD
C$-FF6#QCPhuong~trinh~khong~co~dang~bac~2.|+F$OF$C$>Fbu7#-Fh`l6$FDFcal?(F[_lFgn
Fgn-FhclF]yF`dl-FF6$QP+~Neu~m~=~%a:~Phuong~trinh~khong~co~dang~bac~2|+F$&FbuFa`
l@%-Fb_l6$FjsFd_l@'2FjsFB-FF6#Fi^l/FjsFB-FF6$QBPhuong~trinh~co~nghiem~kep:~~%a~
|+F$/Fc^lFcqC$-FF6#QDPhuong~trinh~co~nghiem~phan~biet!~|+F$-Fgo6$/%#x1G,$*&,&F;
F_p-Fap6#FjsFgnFgnF2F_pFdp/%#x2G,$*&,&F;FgnFgbmFgnFgnF2F_pFeqC.-FF6#Q/1/~delta~
<~0:|+F$>Fh^l7$-Fh`l6#FdamFcal?(F[_lFgnFgn-FhclFc`lF`dl-FF6$QO+~Voi~m=~%a~~&Imp
lies;~Phuong~trinh~vo~nghiem|+F$&Fh^lFa`l-FF6#Fjal-FF6#Q/2/~delta~=~0:|+F$>Fh^l
7$-Fh`l6#FgamFcal?(F[_lFgnFgnFgcmF`dlC$-FF6$Q2+~Voi~m~=~%a~~=>~F$F[dm-FF6&Q,Ngh
iem~kep~F$F[_lQ'~=~%a|+F$-F_al6$/FcalF[dmFcqF\dm-FF6#Q/3/~delta~>~0:|+F$>Fh^l7$
-Fh`l6#2FBFjsFcal-FF6$Q^o+~Voi~m~thuoc:~%a~~&Implies;~Phuong~trinh~co~hai~nghie
m~phan~biet!|+F$Fh^lF`bmF$F$F$6#F9I&checkGFIt+F)6$%$numG%"fGF$F$C'>FZF\il>F2-%'
expandGFj\l@$/FZF9--F\dl6#&F"6#F'Fb[m@$/FZFfs--F\dl6#&F"6#F\sFb[m@$30FZF90FZFfs
-FF6#Q>Khong~the~giai~phuong~trinh.|+F$F$F$F$6#FgnF$
